using System.Collections.Generic;

namespace Kanal.Host.Localization;

/// <summary>
/// Every string the operator reads, in the four languages the host is offered in. English is the
/// source of truth; a test asserts the other three carry exactly the same keys, so a string added
/// to one screen cannot quietly go missing on three others.
/// </summary>
/// <remarks>
/// Plain dictionaries rather than RESX: the set is small enough to read in one file, diffs across
/// four languages line up side by side, and nothing has to be regenerated to add a string. The
/// register is the one <c>.impeccable.md</c> asks for in every language — terse and factual, an
/// instrument rather than a product. Where a string tells the operator what went wrong it also
/// says what to do about it, in all four.
/// </remarks>
public static class Strings
{
    private static readonly IReadOnlyDictionary<string, string> En = new Dictionary<string, string>
    {
        // masthead + transport
        ["mode.label"] = "MODE",
        ["languages.label"] = "LANGUAGES",
        ["input.label"] = "INPUT",
        ["transport.start"] = "Start",
        ["transport.pause"] = "Pause",
        ["transport.resume"] = "Resume",
        ["transport.stop"] = "Stop",
        ["transport.pause.tip"] = "Take the room off the record — nothing transcribed, translated or sent. The room, the QR and the transcript all stay.",
        ["export.button"] = "Export .md",
        ["settings.tip"] = "Settings",
        ["languages.tip"] = "Room languages — click to edit",
        ["languages.none"] = "none — click to add",
        ["paused.band"] = "PAUSED — NOTHING IS BEING TRANSCRIBED, TRANSLATED OR SENT",
        ["recording.on"] = "RECORDING",
        ["recording.held"] = "RECORDING HELD",

        // mode help flyout
        ["modes.tip"] = "What the modes mean",
        ["modes.heading"] = "MODES",
        ["modes.intro"] = "Kanal runs two stages — speech into text, then text into the other languages — and each one can run on this laptop or off it. A mode picks both at once. Modes that cannot run yet stay in the list with the reason.",
        ["mode.status.ready"] = "ready",

        // modes
        ["mode.demo.name"] = "Demo — scripted",
        ["mode.demo.help"] = "A fixed script of six utterances, looping. No microphone, no account, no network — for checking the room's screens, the join QR and the phones before anyone arrives.",
        ["mode.cloudcloud.name"] = "Cloud transcription · cloud translation",
        ["mode.cloudcloud.help"] = "Both stages run off this machine in one streaming session. The fastest and the most accurate option available today, and the one that sends the room's audio out. Needs an API key.",
        ["mode.cloudlocal.name"] = "Cloud transcription · local translation",
        ["mode.cloudlocal.help"] = "Speech is transcribed off this machine; the transcript is then translated here by a downloaded model, so the wording never leaves. The audio still does. Needs an API key and a translation model.",
        ["mode.localcloud.name"] = "Local transcription · cloud translation",
        ["mode.localcloud.help"] = "Speech never leaves the room — only the transcript is sent out to be translated. The cheapest way to buy good translation, and the only mode that satisfies the goal this tool was built around. Waiting on local transcription.",
        ["mode.locallocal.name"] = "Local transcription · local translation",
        ["mode.locallocal.help"] = "Everything runs on this laptop and nothing is sent anywhere. The strongest privacy position and the heaviest on the machine. Waiting on local transcription.",
        ["leaves.nothing"] = "nothing leaves this machine",
        ["leaves.audio"] = "audio leaves this machine",
        ["leaves.text"] = "only text leaves this machine",

        // resolved pipeline, printed in the masthead
        ["stage.transcription.scripted"] = "Transcription: scripted",
        ["stage.transcription.localsoon"] = "Transcription: local — not available yet",
        ["stage.transcription.nokey"] = "Transcription: cloud — no key",
        ["stage.transcription.named"] = "Transcription: cloud — key “{0}”",
        ["stage.transcription.env"] = "Transcription: cloud — key from the environment",
        ["stage.translation.cloud"] = "Translation: cloud",
        ["stage.translation.cloudsoon"] = "Translation: cloud — not available yet",
        ["stage.translation.scripted"] = "Translation: scripted",
        ["stage.translation.nomodel"] = "Translation: no model selected",
        ["stage.translation.unknown"] = "Translation: unknown model \"{0}\"",
        ["stage.translation.notdownloaded"] = "Translation: {0} — not downloaded",
        ["stage.translation.local"] = "Translation: {0} (local)",

        // why a mode cannot run
        ["reason.localasr"] = "local transcription is not built yet",
        ["reason.cloudmt"] = "no standalone cloud translation provider yet — cloud translation only runs inside a cloud transcription session",
        ["reason.nokey"] = "no API key — add one in Settings",
        ["reason.nomodel"] = "no translation model selected — pick one in Settings",
        ["reason.unknownmodel"] = "unknown translation model “{0}” — pick one in Settings",
        ["reason.notdownloaded"] = "{0} is not downloaded — open Settings",
        ["reason.substitute"] = "{0} Using scripted translations.",

        // before the first Start
        ["empty.heading"] = "NO ROOM YET",
        ["empty.body1"] = "Pick the languages spoken in the room, then Start. One column per language, newest utterance at the bottom.",
        ["empty.body2"] = "The mode picks both stages — where speech is transcribed and where it is translated — and says what leaves this machine. Demo needs no key. A join QR appears on the right; everyone else reads on their own phone, in their own language.",

        // right-hand panel
        ["join.label"] = "JOIN",
        ["speakers.label"] = "SPEAKERS",
        ["merge.label"] = "MERGE",
        ["merge.button"] = "Merge",
        ["speaker.placeholder"] = "display name",
        ["speaker.apply.tip"] = "Apply name (or press Enter)",

        // columns
        ["column.original"] = "· ORIGINAL",
        ["column.original.tip"] = "Spoken in this language — transcript, not a translation",
        ["column.codeswitch.tip"] = "Mixed language",
        ["column.drag.tip"] = "Drag to move this column — or Alt+← / Alt+→",

        // status line
        ["status.idle"] = "Idle.",
        ["status.pickalanguage"] = "Select at least one language.",
        ["status.demorunning"] = "Demo running.",
        ["status.live"] = "Live — {0}.",
        ["status.paused"] = "Paused — nothing is being transcribed, translated or sent. The room stays open.",
        ["status.stopping"] = "Stopping…",
        ["status.stopped"] = "Stopped. Rename, merge and export still work on the last room.",
        ["status.stopped.audio"] = "Stopped. Audio saved to {0}. Rename, merge and export still work.",
        ["status.startfailed"] = "Start failed: {0}",
        ["status.sessionended"] = "Session ended: {0}",
        ["status.done"] = "done",
        ["status.fatal"] = "Fatal: {0}",
        ["status.warning"] = "Warning: {0}",
        ["status.nothingtoexport"] = "Nothing to export.",
        ["status.exportcancelled"] = "Export cancelled.",
        ["status.exported"] = "Exported to {0}",
        ["status.exported.audio"] = "Exported to {0} · audio: {1}",
        ["status.exportfailed"] = "Export failed: {0}",
        ["status.nobackend"] = "No audio capture backend on this platform.",
        ["status.audiofailed"] = "Audio capture failed: {0}",
        ["status.notrecording"] = "Not recording: {0}",
        ["status.recordingstopped"] = "Recording stopped: {0}",
        ["status.snapshotfailed"] = "snapshot publish failed: {0}",
        ["status.closefailed"] = "close notice failed: {0}",
        ["status.publishfailed"] = "relay publish failed: {0}",

        // room languages dialog
        ["langdlg.title"] = "Room languages",
        ["langdlg.heading"] = "ROOM LANGUAGES",
        ["langdlg.placeholder"] = "Other ISO codes — tr, nl",
        ["langdlg.add"] = "Add",
        ["langdlg.note"] = "Up to four languages. Each one is a column on this screen, translated, and a choice on the phones.",
        ["langdlg.done"] = "Done",
        ["langdlg.limit"] = "Four columns maximum — deselect one to add another.",

        // settings
        ["settings.title"] = "Kanal — Settings",
        ["settings.save"] = "Save & Close",
        ["settings.applang.heading"] = "LANGUAGE",
        ["settings.applang.label"] = "This application",
        ["settings.applang.note"] = "The labels and messages on this screen. Separate from the room languages, which are what gets translated for the people in the meeting.",
        ["settings.input.heading"] = "INPUT",
        ["settings.input.title"] = "Test a microphone",
        ["settings.input.test"] = "Test",
        ["settings.input.stop"] = "Stop",
        ["settings.input.note"] = "Kanal applies no noise suppression, echo cancellation or automatic gain of its own. Whatever the microphone and Windows do to the signal happens before Kanal sees it, and is configured per device in Windows sound settings — this test measures the result.",
        ["mic.untested"] = "Not tested",
        ["mic.untested.detail"] = "Start the test and speak from where people will actually sit.",
        ["mic.listening"] = "Listening…",
        ["mic.listening.detail"] = "Speak from where people will actually sit, then leave a few seconds of quiet.",
        ["mic.nobackend"] = "No audio backend",
        ["mic.nobackend.detail"] = "This platform has no capture support built in yet.",
        ["mic.failed"] = "Could not open the microphone",
        ["mic.silent"] = "Nothing is arriving",
        ["mic.silent.detail"] = "Check that this is the right device and that Windows has not muted or disabled it.",
        ["mic.quiet"] = "Too quiet",
        ["mic.quiet.detail"] = "Raise the input level in Windows sound settings, or put the microphone nearer the table.",
        ["mic.clipping"] = "Clipping",
        ["mic.clipping.detail"] = "Lower the input level in Windows sound settings. A clipped consonant is gone for good — no transcriber recovers it.",
        ["mic.noisy"] = "The room is nearly as loud as the speaker",
        ["mic.noisy.detail"] = "Speech is only {0} dB above the room. Move the microphone closer to the talkers, or turn off whatever is making the noise.",
        ["mic.good"] = "Good",
        ["mic.good.detail"] = "Speech sits {0} dB above the room.",
        ["mic.good.silentroom"] = "Speech peaks at {0} dB and the gaps are completely silent — either a very quiet room, or the device is gating the signal.",
        ["mic.readout"] = "peak {0} dB · room {1} dB · margin {2} dB",
        ["mic.readout.silentroom"] = "peak {0} dB · room silent",
        ["settings.transcription.heading"] = "TRANSCRIPTION",
        ["settings.transcription.keys"] = "Cloud provider — Gladia API keys",
        ["settings.env.set"] = "Fallback: {0} env var is set.",
        ["settings.env.unset"] = "Fallback: {0} env var is not set.",
        ["settings.usekey.tip"] = "Use this key",
        ["settings.addkey"] = "ADD A KEY",
        ["settings.key.name"] = "name (e.g. work)",
        ["settings.key.value"] = "API key",
        ["settings.add"] = "Add",
        ["settings.localasr.note"] = "Local transcription — not built yet.",
        ["settings.translation.heading"] = "TRANSLATION",
        ["settings.translation.localmodel"] = "Local model",
        ["settings.translation.note"] = "Downloaded once; after that no translated text leaves this machine. Used by the local-translation modes.",
        ["settings.translation.cloudnote"] = "Cloud provider — none yet. Cloud translation runs inside the cloud transcription session, so it needs no key of its own.",
        ["settings.model.usetip"] = "Use for translation",
        ["settings.model.download"] = "Download",
        ["settings.model.cancel"] = "Cancel",
        ["settings.model.delete"] = "Delete",
        ["settings.files.heading"] = "FILES",
        ["settings.files.title"] = "Where meetings are saved",
        ["settings.files.note"] = "The export dialog opens on the transcript folder; the file name and place can still be changed there every time.",
        ["settings.files.default"] = "Empty means {0}",
        ["settings.files.transcripts"] = "TRANSCRIPTS",
        ["settings.files.audio"] = "AUDIO",
        ["settings.files.placeholder"] = "default",
        ["settings.browse"] = "Browse…",
        ["settings.browse.title"] = "Choose a folder",
        ["settings.record"] = "Record the room to disk while a meeting runs",
        ["settings.record.note"] = "One file per meeting, named after the room. About 115 MB an hour. The recording never leaves this machine and is not written while the meeting is paused.",
        ["export.dialog.title"] = "Save transcript",
    };

    private static readonly IReadOnlyDictionary<string, string> Zh = new Dictionary<string, string>
    {
        ["mode.label"] = "模式",
        ["languages.label"] = "语言",
        ["input.label"] = "输入",
        ["transport.start"] = "开始",
        ["transport.pause"] = "暂停",
        ["transport.resume"] = "继续",
        ["transport.stop"] = "结束",
        ["transport.pause.tip"] = "暂不记录本房间——不转写、不翻译、不发送。房间、二维码和已有记录都保留。",
        ["export.button"] = "导出 .md",
        ["settings.tip"] = "设置",
        ["languages.tip"] = "房间语言——点击修改",
        ["languages.none"] = "未选——点击添加",
        ["paused.band"] = "已暂停 —— 不转写、不翻译、不发送",
        ["recording.on"] = "录音中",
        ["recording.held"] = "录音已暂停",

        ["modes.tip"] = "各模式的含义",
        ["modes.heading"] = "模式",
        ["modes.intro"] = "Kanal 分两个阶段运行——先把语音转成文字，再把文字翻成其他语言——每个阶段都可以在本机或本机之外运行。一个模式同时决定两者。暂时无法运行的模式仍留在列表中，并注明原因。",
        ["mode.status.ready"] = "可用",

        ["mode.demo.name"] = "演示 —— 脚本",
        ["mode.demo.help"] = "六句固定台词循环播放。不用麦克风、不用账号、不联网——供开会前检查会场屏幕、入会二维码和手机页面。",
        ["mode.cloudcloud.name"] = "云端转写 · 云端翻译",
        ["mode.cloudcloud.help"] = "两个阶段都在本机之外的同一个流式会话中完成。目前最快也最准确的选择，同时也是会把会场音频发出去的那一个。需要 API 密钥。",
        ["mode.cloudlocal.name"] = "云端转写 · 本地翻译",
        ["mode.cloudlocal.help"] = "语音在本机之外转写；转写结果随后由本机下载的模型翻译，因此译文措辞不会外传。音频仍会外传。需要 API 密钥和一个翻译模型。",
        ["mode.localcloud.name"] = "本地转写 · 云端翻译",
        ["mode.localcloud.help"] = "语音不出会议室——只把文字发出去翻译。这是买到好翻译最省钱的方式，也是唯一符合本工具设计初衷的模式。等待本地转写完成开发。",
        ["mode.locallocal.name"] = "本地转写 · 本地翻译",
        ["mode.locallocal.help"] = "全部在本机运行，什么都不外传。隐私最强，对机器的负担也最重。等待本地转写完成开发。",
        ["leaves.nothing"] = "没有任何内容离开本机",
        ["leaves.audio"] = "音频会离开本机",
        ["leaves.text"] = "只有文字离开本机",

        ["stage.transcription.scripted"] = "转写：脚本",
        ["stage.transcription.localsoon"] = "转写：本地——尚不可用",
        ["stage.transcription.nokey"] = "转写：云端——无密钥",
        ["stage.transcription.named"] = "转写：云端——密钥“{0}”",
        ["stage.transcription.env"] = "转写：云端——来自环境变量的密钥",
        ["stage.translation.cloud"] = "翻译：云端",
        ["stage.translation.cloudsoon"] = "翻译：云端——尚不可用",
        ["stage.translation.scripted"] = "翻译：脚本",
        ["stage.translation.nomodel"] = "翻译：未选择模型",
        ["stage.translation.unknown"] = "翻译：未知模型“{0}”",
        ["stage.translation.notdownloaded"] = "翻译：{0}——未下载",
        ["stage.translation.local"] = "翻译：{0}（本地）",

        ["reason.localasr"] = "本地转写尚未开发",
        ["reason.cloudmt"] = "还没有独立的云端翻译服务——云端翻译目前只能在云端转写会话内部运行",
        ["reason.nokey"] = "没有 API 密钥——请在设置中添加",
        ["reason.nomodel"] = "未选择翻译模型——请在设置中选择",
        ["reason.unknownmodel"] = "未知的翻译模型“{0}”——请在设置中选择",
        ["reason.notdownloaded"] = "{0} 尚未下载——请打开设置",
        ["reason.substitute"] = "{0} 现使用脚本译文。",

        ["empty.heading"] = "尚未开始",
        ["empty.body1"] = "先选好会议室里要说的语言，然后点开始。每种语言一列，最新的一句在最下面。",
        ["empty.body2"] = "模式同时决定两个阶段——在哪里转写、在哪里翻译——并说明什么会离开本机。演示模式不需要密钥。右侧会出现入会二维码；其他人用自己的手机、按自己的语言阅读。",

        ["join.label"] = "入会",
        ["speakers.label"] = "发言人",
        ["merge.label"] = "合并",
        ["merge.button"] = "合并",
        ["speaker.placeholder"] = "显示名称",
        ["speaker.apply.tip"] = "应用名称（或按回车）",

        ["column.original"] = "· 原文",
        ["column.original.tip"] = "用这种语言说出——转写，不是译文",
        ["column.codeswitch.tip"] = "混合语种",
        ["column.drag.tip"] = "拖动可移动此列——或按 Alt+← / Alt+→",

        ["status.idle"] = "空闲。",
        ["status.pickalanguage"] = "请至少选择一种语言。",
        ["status.demorunning"] = "演示进行中。",
        ["status.live"] = "进行中——{0}。",
        ["status.paused"] = "已暂停——不转写、不翻译、不发送。房间保持开启。",
        ["status.stopping"] = "正在结束…",
        ["status.stopped"] = "已结束。重命名、合并和导出仍可用于上一场会议。",
        ["status.stopped.audio"] = "已结束。音频已保存至 {0}。重命名、合并和导出仍可用。",
        ["status.startfailed"] = "启动失败：{0}",
        ["status.sessionended"] = "会话结束：{0}",
        ["status.done"] = "完成",
        ["status.fatal"] = "严重错误：{0}",
        ["status.warning"] = "警告：{0}",
        ["status.nothingtoexport"] = "没有可导出的内容。",
        ["status.exportcancelled"] = "已取消导出。",
        ["status.exported"] = "已导出至 {0}",
        ["status.exported.audio"] = "已导出至 {0} · 音频：{1}",
        ["status.exportfailed"] = "导出失败：{0}",
        ["status.nobackend"] = "本平台暂无音频采集后端。",
        ["status.audiofailed"] = "音频采集失败：{0}",
        ["status.notrecording"] = "未录音：{0}",
        ["status.recordingstopped"] = "录音已停止：{0}",
        ["status.snapshotfailed"] = "快照发布失败：{0}",
        ["status.closefailed"] = "结束通知发送失败：{0}",
        ["status.publishfailed"] = "转发发布失败：{0}",

        ["langdlg.title"] = "房间语言",
        ["langdlg.heading"] = "房间语言",
        ["langdlg.placeholder"] = "其他 ISO 代码——tr、nl",
        ["langdlg.add"] = "添加",
        ["langdlg.note"] = "最多四种语言。每种在本屏幕上占一列并被翻译，同时成为手机端的一个选项。",
        ["langdlg.done"] = "完成",
        ["langdlg.limit"] = "最多四列——请先取消一种再添加。",

        ["settings.title"] = "Kanal —— 设置",
        ["settings.save"] = "保存并关闭",
        ["settings.applang.heading"] = "界面语言",
        ["settings.applang.label"] = "本应用",
        ["settings.applang.note"] = "本屏幕上的标签和提示。与房间语言无关——房间语言是为参会者翻译的内容。",
        ["settings.input.heading"] = "输入",
        ["settings.input.title"] = "测试麦克风",
        ["settings.input.test"] = "测试",
        ["settings.input.stop"] = "停止",
        ["settings.input.note"] = "Kanal 自身不做任何降噪、回声消除或自动增益。麦克风和 Windows 对信号做的处理都发生在 Kanal 拿到采样之前，并且是在 Windows 声音设置中按设备配置的——本测试测量的是处理之后的结果。",
        ["mic.untested"] = "尚未测试",
        ["mic.untested.detail"] = "开始测试，并站在参会者实际就座的位置说话。",
        ["mic.listening"] = "正在监听…",
        ["mic.listening.detail"] = "在参会者实际就座的位置说几句，然后安静几秒。",
        ["mic.nobackend"] = "无音频后端",
        ["mic.nobackend.detail"] = "本平台尚未内置采集支持。",
        ["mic.failed"] = "无法打开麦克风",
        ["mic.silent"] = "没有信号进来",
        ["mic.silent.detail"] = "请确认设备选对了，并且 Windows 没有将其静音或禁用。",
        ["mic.quiet"] = "声音太小",
        ["mic.quiet.detail"] = "请在 Windows 声音设置中调高输入音量，或把麦克风放得离桌子更近。",
        ["mic.clipping"] = "已削波",
        ["mic.clipping.detail"] = "请在 Windows 声音设置中调低输入音量。被削掉的辅音再也回不来——任何转写系统都无法还原。",
        ["mic.noisy"] = "环境噪声几乎和说话人一样大",
        ["mic.noisy.detail"] = "人声仅比环境高 {0} dB。请把麦克风移近说话的人，或关掉噪声源。",
        ["mic.good"] = "良好",
        ["mic.good.detail"] = "人声比环境高 {0} dB。",
        ["mic.good.silentroom"] = "人声峰值 {0} dB，间隙完全无声——要么房间非常安静，要么设备对信号做了门限处理。",
        ["mic.readout"] = "峰值 {0} dB · 环境 {1} dB · 余量 {2} dB",
        ["mic.readout.silentroom"] = "峰值 {0} dB · 环境无声",
        ["settings.transcription.heading"] = "转写",
        ["settings.transcription.keys"] = "云服务商 —— Gladia API 密钥",
        ["settings.env.set"] = "备用：环境变量 {0} 已设置。",
        ["settings.env.unset"] = "备用：环境变量 {0} 未设置。",
        ["settings.usekey.tip"] = "使用此密钥",
        ["settings.addkey"] = "添加密钥",
        ["settings.key.name"] = "名称（例如 work）",
        ["settings.key.value"] = "API 密钥",
        ["settings.add"] = "添加",
        ["settings.localasr.note"] = "本地转写——尚未开发。",
        ["settings.translation.heading"] = "翻译",
        ["settings.translation.localmodel"] = "本地模型",
        ["settings.translation.note"] = "只需下载一次；此后译文不会离开本机。供本地翻译类模式使用。",
        ["settings.translation.cloudnote"] = "云服务商——暂无。云端翻译在云端转写会话内部运行，因此不需要单独的密钥。",
        ["settings.model.usetip"] = "用于翻译",
        ["settings.model.download"] = "下载",
        ["settings.model.cancel"] = "取消",
        ["settings.model.delete"] = "删除",
        ["settings.files.heading"] = "文件",
        ["settings.files.title"] = "会议保存位置",
        ["settings.files.note"] = "导出对话框会从记录文件夹打开；每次仍可在对话框里改文件名和位置。",
        ["settings.files.default"] = "留空表示 {0}",
        ["settings.files.transcripts"] = "记录",
        ["settings.files.audio"] = "音频",
        ["settings.files.placeholder"] = "默认",
        ["settings.browse"] = "浏览…",
        ["settings.browse.title"] = "选择文件夹",
        ["settings.record"] = "会议进行时把会场录到磁盘",
        ["settings.record.note"] = "每场会议一个文件，以房间号命名。约每小时 115 MB。录音不会离开本机，暂停期间也不写入。",
        ["export.dialog.title"] = "保存会议记录",
    };

    private static readonly IReadOnlyDictionary<string, string> De = new Dictionary<string, string>
    {
        ["mode.label"] = "MODUS",
        ["languages.label"] = "SPRACHEN",
        ["input.label"] = "EINGANG",
        ["transport.start"] = "Start",
        ["transport.pause"] = "Pause",
        ["transport.resume"] = "Weiter",
        ["transport.stop"] = "Stopp",
        ["transport.pause.tip"] = "Den Raum aus der Aufzeichnung nehmen — nichts wird transkribiert, übersetzt oder gesendet. Raum, QR-Code und Protokoll bleiben erhalten.",
        ["export.button"] = "Export .md",
        ["settings.tip"] = "Einstellungen",
        ["languages.tip"] = "Sprachen im Raum — zum Ändern klicken",
        ["languages.none"] = "keine — zum Hinzufügen klicken",
        ["paused.band"] = "PAUSIERT — ES WIRD NICHTS TRANSKRIBIERT, ÜBERSETZT ODER GESENDET",
        ["recording.on"] = "AUFNAHME",
        ["recording.held"] = "AUFNAHME ANGEHALTEN",

        ["modes.tip"] = "Was die Modi bedeuten",
        ["modes.heading"] = "MODI",
        ["modes.intro"] = "Kanal arbeitet in zwei Stufen — Sprache zu Text, dann Text in die anderen Sprachen — und jede kann auf diesem Laptop oder außerhalb laufen. Ein Modus wählt beide zugleich. Modi, die noch nicht laufen können, bleiben mit der Begründung in der Liste.",
        ["mode.status.ready"] = "bereit",

        ["mode.demo.name"] = "Demo — Skript",
        ["mode.demo.help"] = "Sechs feste Sätze in Dauerschleife. Kein Mikrofon, kein Konto, kein Netz — zum Prüfen der Bildschirme, des QR-Codes und der Telefone, bevor jemand da ist.",
        ["mode.cloudcloud.name"] = "Cloud-Transkription · Cloud-Übersetzung",
        ["mode.cloudcloud.help"] = "Beide Stufen laufen außerhalb dieses Rechners in einer Streaming-Sitzung. Die schnellste und genaueste Option, die es heute gibt — und die einzige, die den Ton des Raums nach außen gibt. Braucht einen API-Schlüssel.",
        ["mode.cloudlocal.name"] = "Cloud-Transkription · lokale Übersetzung",
        ["mode.cloudlocal.help"] = "Die Sprache wird außerhalb transkribiert, das Transkript danach hier von einem heruntergeladenen Modell übersetzt — die Formulierungen verlassen den Rechner also nie. Der Ton weiterhin schon. Braucht einen API-Schlüssel und ein Übersetzungsmodell.",
        ["mode.localcloud.name"] = "Lokale Transkription · Cloud-Übersetzung",
        ["mode.localcloud.help"] = "Die Sprache verlässt den Raum nicht — nur das Transkript geht zur Übersetzung hinaus. Der günstigste Weg zu guter Übersetzung und der einzige Modus, der dem Ziel dieses Werkzeugs entspricht. Wartet auf die lokale Transkription.",
        ["mode.locallocal.name"] = "Lokale Transkription · lokale Übersetzung",
        ["mode.locallocal.help"] = "Alles läuft auf diesem Laptop, nichts wird versendet. Der stärkste Datenschutz und die höchste Last für die Maschine. Wartet auf die lokale Transkription.",
        ["leaves.nothing"] = "nichts verlässt diesen Rechner",
        ["leaves.audio"] = "der Ton verlässt diesen Rechner",
        ["leaves.text"] = "nur Text verlässt diesen Rechner",

        ["stage.transcription.scripted"] = "Transkription: Skript",
        ["stage.transcription.localsoon"] = "Transkription: lokal — noch nicht verfügbar",
        ["stage.transcription.nokey"] = "Transkription: Cloud — kein Schlüssel",
        ["stage.transcription.named"] = "Transkription: Cloud — Schlüssel „{0}“",
        ["stage.transcription.env"] = "Transkription: Cloud — Schlüssel aus der Umgebung",
        ["stage.translation.cloud"] = "Übersetzung: Cloud",
        ["stage.translation.cloudsoon"] = "Übersetzung: Cloud — noch nicht verfügbar",
        ["stage.translation.scripted"] = "Übersetzung: Skript",
        ["stage.translation.nomodel"] = "Übersetzung: kein Modell gewählt",
        ["stage.translation.unknown"] = "Übersetzung: unbekanntes Modell \"{0}\"",
        ["stage.translation.notdownloaded"] = "Übersetzung: {0} — nicht heruntergeladen",
        ["stage.translation.local"] = "Übersetzung: {0} (lokal)",

        ["reason.localasr"] = "die lokale Transkription ist noch nicht gebaut",
        ["reason.cloudmt"] = "noch kein eigenständiger Cloud-Übersetzungsdienst — Cloud-Übersetzung läuft bisher nur innerhalb einer Cloud-Transkriptionssitzung",
        ["reason.nokey"] = "kein API-Schlüssel — in den Einstellungen hinterlegen",
        ["reason.nomodel"] = "kein Übersetzungsmodell gewählt — in den Einstellungen auswählen",
        ["reason.unknownmodel"] = "unbekanntes Übersetzungsmodell „{0}“ — in den Einstellungen auswählen",
        ["reason.notdownloaded"] = "{0} ist nicht heruntergeladen — Einstellungen öffnen",
        ["reason.substitute"] = "{0} Es werden Skript-Übersetzungen verwendet.",

        ["empty.heading"] = "NOCH KEIN RAUM",
        ["empty.body1"] = "Die im Raum gesprochenen Sprachen wählen, dann Start. Eine Spalte je Sprache, der neueste Beitrag unten.",
        ["empty.body2"] = "Der Modus wählt beide Stufen — wo transkribiert und wo übersetzt wird — und nennt, was diesen Rechner verlässt. Demo braucht keinen Schlüssel. Rechts erscheint ein QR-Code zum Beitreten; alle anderen lesen auf dem eigenen Telefon, in der eigenen Sprache.",

        ["join.label"] = "BEITRETEN",
        ["speakers.label"] = "SPRECHER",
        ["merge.label"] = "ZUSAMMENFÜHREN",
        ["merge.button"] = "Zusammenführen",
        ["speaker.placeholder"] = "Anzeigename",
        ["speaker.apply.tip"] = "Namen übernehmen (oder Eingabetaste)",

        ["column.original"] = "· ORIGINAL",
        ["column.original.tip"] = "In dieser Sprache gesprochen — Transkript, keine Übersetzung",
        ["column.codeswitch.tip"] = "Gemischte Sprache",
        ["column.drag.tip"] = "Ziehen, um diese Spalte zu verschieben — oder Alt+← / Alt+→",

        ["status.idle"] = "Bereit.",
        ["status.pickalanguage"] = "Mindestens eine Sprache wählen.",
        ["status.demorunning"] = "Demo läuft.",
        ["status.live"] = "Läuft — {0}.",
        ["status.paused"] = "Pausiert — es wird nichts transkribiert, übersetzt oder gesendet. Der Raum bleibt offen.",
        ["status.stopping"] = "Wird beendet…",
        ["status.stopped"] = "Beendet. Umbenennen, Zusammenführen und Export funktionieren weiterhin für den letzten Raum.",
        ["status.stopped.audio"] = "Beendet. Ton gespeichert unter {0}. Umbenennen, Zusammenführen und Export funktionieren weiterhin.",
        ["status.startfailed"] = "Start fehlgeschlagen: {0}",
        ["status.sessionended"] = "Sitzung beendet: {0}",
        ["status.done"] = "fertig",
        ["status.fatal"] = "Schwerwiegend: {0}",
        ["status.warning"] = "Warnung: {0}",
        ["status.nothingtoexport"] = "Nichts zu exportieren.",
        ["status.exportcancelled"] = "Export abgebrochen.",
        ["status.exported"] = "Exportiert nach {0}",
        ["status.exported.audio"] = "Exportiert nach {0} · Ton: {1}",
        ["status.exportfailed"] = "Export fehlgeschlagen: {0}",
        ["status.nobackend"] = "Auf dieser Plattform gibt es keine Audioaufnahme.",
        ["status.audiofailed"] = "Audioaufnahme fehlgeschlagen: {0}",
        ["status.notrecording"] = "Keine Aufnahme: {0}",
        ["status.recordingstopped"] = "Aufnahme gestoppt: {0}",
        ["status.snapshotfailed"] = "Senden des Zwischenstands fehlgeschlagen: {0}",
        ["status.closefailed"] = "Abschlussmeldung fehlgeschlagen: {0}",
        ["status.publishfailed"] = "Senden fehlgeschlagen: {0}",

        ["langdlg.title"] = "Sprachen im Raum",
        ["langdlg.heading"] = "SPRACHEN IM RAUM",
        ["langdlg.placeholder"] = "Weitere ISO-Codes — tr, nl",
        ["langdlg.add"] = "Hinzufügen",
        ["langdlg.note"] = "Bis zu vier Sprachen. Jede ist eine Spalte auf diesem Bildschirm, wird übersetzt und steht auf den Telefonen zur Wahl.",
        ["langdlg.done"] = "Fertig",
        ["langdlg.limit"] = "Höchstens vier Spalten — eine abwählen, um eine andere hinzuzufügen.",

        ["settings.title"] = "Kanal — Einstellungen",
        ["settings.save"] = "Speichern und schließen",
        ["settings.applang.heading"] = "SPRACHE",
        ["settings.applang.label"] = "Diese Anwendung",
        ["settings.applang.note"] = "Die Beschriftungen und Meldungen auf diesem Bildschirm. Unabhängig von den Sprachen im Raum — das ist das, was für die Teilnehmer übersetzt wird.",
        ["settings.input.heading"] = "EINGANG",
        ["settings.input.title"] = "Mikrofon testen",
        ["settings.input.test"] = "Testen",
        ["settings.input.stop"] = "Stopp",
        ["settings.input.note"] = "Kanal wendet selbst keine Rauschunterdrückung, Echounterdrückung oder automatische Aussteuerung an. Was Mikrofon und Windows mit dem Signal machen, geschieht, bevor Kanal es sieht, und wird je Gerät in den Windows-Sound-Einstellungen konfiguriert — dieser Test misst das Ergebnis.",
        ["mic.untested"] = "Nicht getestet",
        ["mic.untested.detail"] = "Test starten und von dort sprechen, wo die Leute tatsächlich sitzen werden.",
        ["mic.listening"] = "Höre zu…",
        ["mic.listening.detail"] = "Von dort sprechen, wo die Leute tatsächlich sitzen werden, dann ein paar Sekunden Ruhe lassen.",
        ["mic.nobackend"] = "Kein Audio-Backend",
        ["mic.nobackend.detail"] = "Für diese Plattform ist noch keine Aufnahme eingebaut.",
        ["mic.failed"] = "Mikrofon konnte nicht geöffnet werden",
        ["mic.silent"] = "Es kommt nichts an",
        ["mic.silent.detail"] = "Prüfen, ob das das richtige Gerät ist und ob Windows es nicht stummgeschaltet oder deaktiviert hat.",
        ["mic.quiet"] = "Zu leise",
        ["mic.quiet.detail"] = "Den Eingangspegel in den Windows-Sound-Einstellungen anheben oder das Mikrofon näher an den Tisch stellen.",
        ["mic.clipping"] = "Übersteuert",
        ["mic.clipping.detail"] = "Den Eingangspegel in den Windows-Sound-Einstellungen senken. Ein abgeschnittener Konsonant ist endgültig weg — keine Transkription holt ihn zurück.",
        ["mic.noisy"] = "Der Raum ist fast so laut wie die Sprecher",
        ["mic.noisy.detail"] = "Die Sprache liegt nur {0} dB über dem Raum. Das Mikrofon näher an die Sprechenden bringen oder die Geräuschquelle abschalten.",
        ["mic.good"] = "Gut",
        ["mic.good.detail"] = "Die Sprache liegt {0} dB über dem Raum.",
        ["mic.good.silentroom"] = "Die Sprache erreicht {0} dB, und die Pausen sind vollkommen still — entweder ein sehr ruhiger Raum, oder das Gerät blendet das Signal aus.",
        ["mic.readout"] = "Spitze {0} dB · Raum {1} dB · Abstand {2} dB",
        ["mic.readout.silentroom"] = "Spitze {0} dB · Raum still",
        ["settings.transcription.heading"] = "TRANSKRIPTION",
        ["settings.transcription.keys"] = "Cloud-Anbieter — Gladia-API-Schlüssel",
        ["settings.env.set"] = "Ersatzweise: Umgebungsvariable {0} ist gesetzt.",
        ["settings.env.unset"] = "Ersatzweise: Umgebungsvariable {0} ist nicht gesetzt.",
        ["settings.usekey.tip"] = "Diesen Schlüssel verwenden",
        ["settings.addkey"] = "SCHLÜSSEL HINZUFÜGEN",
        ["settings.key.name"] = "Name (z. B. work)",
        ["settings.key.value"] = "API-Schlüssel",
        ["settings.add"] = "Hinzufügen",
        ["settings.localasr.note"] = "Lokale Transkription — noch nicht gebaut.",
        ["settings.translation.heading"] = "ÜBERSETZUNG",
        ["settings.translation.localmodel"] = "Lokales Modell",
        ["settings.translation.note"] = "Einmal herunterladen; danach verlässt kein übersetzter Text diesen Rechner. Wird von den Modi mit lokaler Übersetzung genutzt.",
        ["settings.translation.cloudnote"] = "Cloud-Anbieter — noch keiner. Die Cloud-Übersetzung läuft innerhalb der Cloud-Transkriptionssitzung und braucht daher keinen eigenen Schlüssel.",
        ["settings.model.usetip"] = "Zum Übersetzen verwenden",
        ["settings.model.download"] = "Herunterladen",
        ["settings.model.cancel"] = "Abbrechen",
        ["settings.model.delete"] = "Löschen",
        ["settings.files.heading"] = "DATEIEN",
        ["settings.files.title"] = "Wo Besprechungen gespeichert werden",
        ["settings.files.note"] = "Der Export-Dialog öffnet im Protokollordner; Name und Ort lassen sich dort jedes Mal noch ändern.",
        ["settings.files.default"] = "Leer bedeutet {0}",
        ["settings.files.transcripts"] = "PROTOKOLLE",
        ["settings.files.audio"] = "TON",
        ["settings.files.placeholder"] = "Standard",
        ["settings.browse"] = "Durchsuchen…",
        ["settings.browse.title"] = "Ordner wählen",
        ["settings.record"] = "Den Raum während der Besprechung auf die Festplatte aufnehmen",
        ["settings.record.note"] = "Eine Datei je Besprechung, benannt nach dem Raum. Etwa 115 MB pro Stunde. Die Aufnahme verlässt diesen Rechner nicht und wird während einer Pause nicht geschrieben.",
        ["export.dialog.title"] = "Protokoll speichern",
    };

    private static readonly IReadOnlyDictionary<string, string> Pl = new Dictionary<string, string>
    {
        ["mode.label"] = "TRYB",
        ["languages.label"] = "JĘZYKI",
        ["input.label"] = "WEJŚCIE",
        ["transport.start"] = "Start",
        ["transport.pause"] = "Pauza",
        ["transport.resume"] = "Wznów",
        ["transport.stop"] = "Zakończ",
        ["transport.pause.tip"] = "Wstrzymaj zapis — nic nie jest transkrybowane, tłumaczone ani wysyłane. Pokój, kod QR i dotychczasowy zapis zostają.",
        ["export.button"] = "Eksport .md",
        ["settings.tip"] = "Ustawienia",
        ["languages.tip"] = "Języki w pokoju — kliknij, aby zmienić",
        ["languages.none"] = "brak — kliknij, aby dodać",
        ["paused.band"] = "WSTRZYMANE — NIC NIE JEST TRANSKRYBOWANE, TŁUMACZONE ANI WYSYŁANE",
        ["recording.on"] = "NAGRYWANIE",
        ["recording.held"] = "NAGRYWANIE WSTRZYMANE",

        ["modes.tip"] = "Co oznaczają tryby",
        ["modes.heading"] = "TRYBY",
        ["modes.intro"] = "Kanal działa w dwóch etapach — mowa na tekst, potem tekst na pozostałe języki — i każdy z nich może działać na tym laptopie albo poza nim. Tryb wybiera oba naraz. Tryby, które jeszcze nie mogą działać, zostają na liście wraz z powodem.",
        ["mode.status.ready"] = "gotowy",

        ["mode.demo.name"] = "Demo — skrypt",
        ["mode.demo.help"] = "Sześć stałych wypowiedzi w pętli. Bez mikrofonu, bez konta, bez sieci — do sprawdzenia ekranów, kodu QR i telefonów, zanim ktokolwiek przyjdzie.",
        ["mode.cloudcloud.name"] = "Transkrypcja w chmurze · tłumaczenie w chmurze",
        ["mode.cloudcloud.help"] = "Oba etapy działają poza tą maszyną, w jednej sesji strumieniowej. Najszybsza i najdokładniejsza dziś dostępna opcja — i jedyna, która wysyła dźwięk z sali. Wymaga klucza API.",
        ["mode.cloudlocal.name"] = "Transkrypcja w chmurze · tłumaczenie lokalne",
        ["mode.cloudlocal.help"] = "Mowa jest transkrybowana poza tą maszyną; zapis tłumaczy potem pobrany tu model, więc same sformułowania nigdy nie wychodzą. Dźwięk nadal wychodzi. Wymaga klucza API i modelu tłumaczącego.",
        ["mode.localcloud.name"] = "Transkrypcja lokalna · tłumaczenie w chmurze",
        ["mode.localcloud.help"] = "Mowa nie opuszcza sali — na zewnątrz idzie tylko tekst do przetłumaczenia. Najtańszy sposób na dobre tłumaczenie i jedyny tryb zgodny z celem, dla którego to narzędzie powstało. Czeka na transkrypcję lokalną.",
        ["mode.locallocal.name"] = "Transkrypcja lokalna · tłumaczenie lokalne",
        ["mode.locallocal.help"] = "Wszystko działa na tym laptopie i nic nie jest wysyłane. Najmocniejsza ochrona prywatności i największe obciążenie maszyny. Czeka na transkrypcję lokalną.",
        ["leaves.nothing"] = "nic nie opuszcza tej maszyny",
        ["leaves.audio"] = "dźwięk opuszcza tę maszynę",
        ["leaves.text"] = "tę maszynę opuszcza tylko tekst",

        ["stage.transcription.scripted"] = "Transkrypcja: skrypt",
        ["stage.transcription.localsoon"] = "Transkrypcja: lokalna — jeszcze niedostępna",
        ["stage.transcription.nokey"] = "Transkrypcja: chmura — brak klucza",
        ["stage.transcription.named"] = "Transkrypcja: chmura — klucz „{0}”",
        ["stage.transcription.env"] = "Transkrypcja: chmura — klucz ze środowiska",
        ["stage.translation.cloud"] = "Tłumaczenie: chmura",
        ["stage.translation.cloudsoon"] = "Tłumaczenie: chmura — jeszcze niedostępne",
        ["stage.translation.scripted"] = "Tłumaczenie: skrypt",
        ["stage.translation.nomodel"] = "Tłumaczenie: nie wybrano modelu",
        ["stage.translation.unknown"] = "Tłumaczenie: nieznany model \"{0}\"",
        ["stage.translation.notdownloaded"] = "Tłumaczenie: {0} — nie pobrano",
        ["stage.translation.local"] = "Tłumaczenie: {0} (lokalnie)",

        ["reason.localasr"] = "transkrypcja lokalna nie jest jeszcze zbudowana",
        ["reason.cloudmt"] = "brak jeszcze osobnej usługi tłumaczenia w chmurze — tłumaczenie w chmurze działa na razie tylko wewnątrz sesji transkrypcji w chmurze",
        ["reason.nokey"] = "brak klucza API — dodaj go w Ustawieniach",
        ["reason.nomodel"] = "nie wybrano modelu tłumaczącego — wybierz go w Ustawieniach",
        ["reason.unknownmodel"] = "nieznany model tłumaczący „{0}” — wybierz go w Ustawieniach",
        ["reason.notdownloaded"] = "{0} nie został pobrany — otwórz Ustawienia",
        ["reason.substitute"] = "{0} Używane są tłumaczenia ze skryptu.",

        ["empty.heading"] = "JESZCZE NIE MA POKOJU",
        ["empty.body1"] = "Wybierz języki, którymi mówi się w sali, i naciśnij Start. Jedna kolumna na język, najnowsza wypowiedź na dole.",
        ["empty.body2"] = "Tryb wybiera oba etapy — gdzie mowa jest transkrybowana i gdzie tłumaczona — oraz mówi, co opuszcza tę maszynę. Demo nie wymaga klucza. Po prawej pojawi się kod QR; pozostali czytają na własnych telefonach, we własnym języku.",

        ["join.label"] = "DOŁĄCZ",
        ["speakers.label"] = "MÓWIĄCY",
        ["merge.label"] = "SCAL",
        ["merge.button"] = "Scal",
        ["speaker.placeholder"] = "nazwa wyświetlana",
        ["speaker.apply.tip"] = "Zastosuj nazwę (lub naciśnij Enter)",

        ["column.original"] = "· ORYGINAŁ",
        ["column.original.tip"] = "Wypowiedziane w tym języku — zapis, nie tłumaczenie",
        ["column.codeswitch.tip"] = "Mieszany język",
        ["column.drag.tip"] = "Przeciągnij, aby przesunąć tę kolumnę — albo Alt+← / Alt+→",

        ["status.idle"] = "Bezczynny.",
        ["status.pickalanguage"] = "Wybierz co najmniej jeden język.",
        ["status.demorunning"] = "Demo działa.",
        ["status.live"] = "Na żywo — {0}.",
        ["status.paused"] = "Wstrzymane — nic nie jest transkrybowane, tłumaczone ani wysyłane. Pokój pozostaje otwarty.",
        ["status.stopping"] = "Kończenie…",
        ["status.stopped"] = "Zakończone. Zmiana nazw, scalanie i eksport nadal działają dla ostatniego pokoju.",
        ["status.stopped.audio"] = "Zakończone. Dźwięk zapisano w {0}. Zmiana nazw, scalanie i eksport nadal działają.",
        ["status.startfailed"] = "Nie udało się uruchomić: {0}",
        ["status.sessionended"] = "Sesja zakończona: {0}",
        ["status.done"] = "gotowe",
        ["status.fatal"] = "Błąd krytyczny: {0}",
        ["status.warning"] = "Ostrzeżenie: {0}",
        ["status.nothingtoexport"] = "Nie ma czego eksportować.",
        ["status.exportcancelled"] = "Eksport anulowany.",
        ["status.exported"] = "Wyeksportowano do {0}",
        ["status.exported.audio"] = "Wyeksportowano do {0} · dźwięk: {1}",
        ["status.exportfailed"] = "Eksport nie powiódł się: {0}",
        ["status.nobackend"] = "Ta platforma nie ma wbudowanego nagrywania dźwięku.",
        ["status.audiofailed"] = "Nagrywanie dźwięku nie powiodło się: {0}",
        ["status.notrecording"] = "Bez nagrywania: {0}",
        ["status.recordingstopped"] = "Nagrywanie zatrzymane: {0}",
        ["status.snapshotfailed"] = "nie udało się wysłać migawki: {0}",
        ["status.closefailed"] = "nie udało się wysłać informacji o zakończeniu: {0}",
        ["status.publishfailed"] = "nie udało się wysłać danych: {0}",

        ["langdlg.title"] = "Języki w pokoju",
        ["langdlg.heading"] = "JĘZYKI W POKOJU",
        ["langdlg.placeholder"] = "Inne kody ISO — tr, nl",
        ["langdlg.add"] = "Dodaj",
        ["langdlg.note"] = "Najwyżej cztery języki. Każdy to jedna kolumna na tym ekranie, tłumaczona, oraz jedna pozycja do wyboru na telefonach.",
        ["langdlg.done"] = "Gotowe",
        ["langdlg.limit"] = "Najwyżej cztery kolumny — odznacz jeden, aby dodać inny.",

        ["settings.title"] = "Kanal — Ustawienia",
        ["settings.save"] = "Zapisz i zamknij",
        ["settings.applang.heading"] = "JĘZYK",
        ["settings.applang.label"] = "Ta aplikacja",
        ["settings.applang.note"] = "Etykiety i komunikaty na tym ekranie. Niezależne od języków w pokoju, czyli od tego, co jest tłumaczone dla uczestników.",
        ["settings.input.heading"] = "WEJŚCIE",
        ["settings.input.title"] = "Przetestuj mikrofon",
        ["settings.input.test"] = "Testuj",
        ["settings.input.stop"] = "Zatrzymaj",
        ["settings.input.note"] = "Kanal nie stosuje własnej redukcji szumów, usuwania echa ani automatycznej regulacji wzmocnienia. Cokolwiek robią z sygnałem mikrofon i Windows, dzieje się zanim Kanal go zobaczy, i jest ustawiane osobno dla każdego urządzenia w ustawieniach dźwięku Windows — ten test mierzy wynik.",
        ["mic.untested"] = "Nie przetestowano",
        ["mic.untested.detail"] = "Uruchom test i mów z miejsca, w którym faktycznie usiądą ludzie.",
        ["mic.listening"] = "Słucham…",
        ["mic.listening.detail"] = "Mów z miejsca, w którym faktycznie usiądą ludzie, a potem zostaw kilka sekund ciszy.",
        ["mic.nobackend"] = "Brak obsługi dźwięku",
        ["mic.nobackend.detail"] = "Ta platforma nie ma jeszcze wbudowanego nagrywania.",
        ["mic.failed"] = "Nie udało się otworzyć mikrofonu",
        ["mic.silent"] = "Nic nie dociera",
        ["mic.silent.detail"] = "Sprawdź, czy to właściwe urządzenie i czy Windows go nie wyciszył ani nie wyłączył.",
        ["mic.quiet"] = "Za cicho",
        ["mic.quiet.detail"] = "Zwiększ poziom wejścia w ustawieniach dźwięku Windows albo przysuń mikrofon bliżej stołu.",
        ["mic.clipping"] = "Przesterowanie",
        ["mic.clipping.detail"] = "Zmniejsz poziom wejścia w ustawieniach dźwięku Windows. Obcięta spółgłoska przepada na zawsze — żadna transkrypcja jej nie odzyska.",
        ["mic.noisy"] = "Sala jest niemal tak głośna jak mówiący",
        ["mic.noisy.detail"] = "Mowa jest tylko {0} dB powyżej sali. Przysuń mikrofon bliżej mówiących albo wyłącz to, co hałasuje.",
        ["mic.good"] = "Dobrze",
        ["mic.good.detail"] = "Mowa jest {0} dB powyżej sali.",
        ["mic.good.silentroom"] = "Mowa osiąga {0} dB, a przerwy są zupełnie ciche — albo sala jest bardzo cicha, albo urządzenie bramkuje sygnał.",
        ["mic.readout"] = "szczyt {0} dB · sala {1} dB · zapas {2} dB",
        ["mic.readout.silentroom"] = "szczyt {0} dB · sala cicha",
        ["settings.transcription.heading"] = "TRANSKRYPCJA",
        ["settings.transcription.keys"] = "Dostawca w chmurze — klucze API Gladia",
        ["settings.env.set"] = "Zapasowo: zmienna środowiskowa {0} jest ustawiona.",
        ["settings.env.unset"] = "Zapasowo: zmienna środowiskowa {0} nie jest ustawiona.",
        ["settings.usekey.tip"] = "Użyj tego klucza",
        ["settings.addkey"] = "DODAJ KLUCZ",
        ["settings.key.name"] = "nazwa (np. work)",
        ["settings.key.value"] = "klucz API",
        ["settings.add"] = "Dodaj",
        ["settings.localasr.note"] = "Transkrypcja lokalna — jeszcze nie zbudowana.",
        ["settings.translation.heading"] = "TŁUMACZENIE",
        ["settings.translation.localmodel"] = "Model lokalny",
        ["settings.translation.note"] = "Pobierany raz; potem żaden przetłumaczony tekst nie opuszcza tej maszyny. Używany przez tryby z tłumaczeniem lokalnym.",
        ["settings.translation.cloudnote"] = "Dostawca w chmurze — jeszcze żaden. Tłumaczenie w chmurze działa wewnątrz sesji transkrypcji w chmurze, więc nie potrzebuje własnego klucza.",
        ["settings.model.usetip"] = "Użyj do tłumaczenia",
        ["settings.model.download"] = "Pobierz",
        ["settings.model.cancel"] = "Anuluj",
        ["settings.model.delete"] = "Usuń",
        ["settings.files.heading"] = "PLIKI",
        ["settings.files.title"] = "Gdzie zapisywane są spotkania",
        ["settings.files.note"] = "Okno eksportu otwiera się w folderze zapisów; nazwę i miejsce nadal można tam zmienić za każdym razem.",
        ["settings.files.default"] = "Puste oznacza {0}",
        ["settings.files.transcripts"] = "ZAPISY",
        ["settings.files.audio"] = "DŹWIĘK",
        ["settings.files.placeholder"] = "domyślnie",
        ["settings.browse"] = "Przeglądaj…",
        ["settings.browse.title"] = "Wybierz folder",
        ["settings.record"] = "Nagrywaj salę na dysk podczas spotkania",
        ["settings.record.note"] = "Jeden plik na spotkanie, nazwany od pokoju. Około 115 MB na godzinę. Nagranie nie opuszcza tej maszyny i nie jest zapisywane, gdy spotkanie jest wstrzymane.",
        ["export.dialog.title"] = "Zapisz zapis spotkania",
    };

    /// <summary>
    /// Declared last on purpose. Static initialisers run in declaration order, so a table built
    /// above the four dictionaries it indexes is built out of four nulls — and every lookup in
    /// the application then throws rather than falling back.
    /// </summary>
    public static IReadOnlyDictionary<string, IReadOnlyDictionary<string, string>> Tables { get; } =
        new Dictionary<string, IReadOnlyDictionary<string, string>>
        {
            ["en"] = En,
            ["zh"] = Zh,
            ["de"] = De,
            ["pl"] = Pl,
        };
}
